services:
  my_postgres:
    container_name: user_serv_postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=userdb
    volumes:
      - ./docker-volume/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  my_pgadmin:
    container_name: user_serv_pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=mishidevxyz@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - ./docker-volume/pgadmin:/var/lib/pgadmin
    ports:
      - 9000:80